//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.26 at 01:54:18 PM MSK 
//


package ru.yandex.qatools.fsm.beans;

import java.io.Serializable;


public class TestBrokenState extends TestFailureState implements Serializable {
}
