//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.28 at 12:24:39 AM MSK 
//


package ru.yandex.qatools.fsm.beans;

import java.io.Serializable;


public class TestsCountByDayState implements Serializable {

    protected long countByDay;

    /**
     * Gets the value of the countByDay property.
     */
    public long getCountByDay() {
        return countByDay;
    }

    /**
     * Sets the value of the countByDay property.
     */
    public void setCountByDay(long value) {
        this.countByDay = value;
    }

}
